##### End of variables to change

onvif_server_v1614_DIR = onvif_server_v16.14

all:
	cd $(onvif_server_v1614_DIR) ; $(MAKE)
	@echo

clean:
	cd $(onvif_server_v1614_DIR) ; $(MAKE) clean

distclean: clean
	-rm -f $(onvif_server_v1614_DIR)/Makefile
